blank_issues_enabled: false
contact_links:
    - name: StarLight Documentation
      url: https://github.com/MaheshSharan/star-core
      about: Comprehensive documentation for using and contributing to StarLight. (might be out of date, check the README for the latest docs!)
    - name: StarLight Issue Tracker
      url: https://github.com/MaheshSharan/star-core/issues
      about: For technical issues, bugs, and feature requests related to StarLight.
